// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK_VlLodLsXbI4jfpUdvoPVXGIJ1Umbqk',
    appId: '1:872379647556:web:330d69f2cb568df2655e11',
    messagingSenderId: '872379647556',
    projectId: 'project-etb',
    authDomain: 'project-etb.firebaseapp.com',
    storageBucket: 'project-etb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSnFkGJKBOPZf243X0RJVU5QPcX1rRDI',
    appId: '1:872379647556:android:b5950c70255eaae2655e11',
    messagingSenderId: '872379647556',
    projectId: 'project-etb',
    storageBucket: 'project-etb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLMCVG95Rl9FT9vP3RbyP6oB1S8pChkQ',
    appId: '1:872379647556:ios:000dc17d4fc4777e655e11',
    messagingSenderId: '872379647556',
    projectId: 'project-etb',
    storageBucket: 'project-etb.firebasestorage.app',
    iosBundleId: 'com.example.etb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLMCVG95Rl9FT9vP3RbyP6oB1S8pChkQ',
    appId: '1:872379647556:ios:000dc17d4fc4777e655e11',
    messagingSenderId: '872379647556',
    projectId: 'project-etb',
    storageBucket: 'project-etb.firebasestorage.app',
    iosBundleId: 'com.example.etb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK_VlLodLsXbI4jfpUdvoPVXGIJ1Umbqk',
    appId: '1:872379647556:web:76db6694dfa4c6e2655e11',
    messagingSenderId: '872379647556',
    projectId: 'project-etb',
    authDomain: 'project-etb.firebaseapp.com',
    storageBucket: 'project-etb.firebasestorage.app',
  );
}
